name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  set-build-info:
    runs-on: ubuntu-latest
    outputs:
      now: ${{ steps.buildinfo.outputs.now }}
      repo: ${{ steps.buildinfo.outputs.repo }}
      branch: ${{ steps.buildinfo.outputs.branch }}
      qualifier: ${{ steps.qualifierinfo.outputs.qualifier }}
    steps:
      - name: Set now, repo, branch, build num
        id: buildinfo
        run: |
          echo "now=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          if [ "${{ github.repository }}" == 'openziti/ziti-sdk-csharp' ]; then
            echo "repo=" >> $GITHUB_OUTPUT
          else
            echo "repo=-${{github.repository_owner}}" >> $GITHUB_OUTPUT
          fi
          echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV
          echo "branch=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_OUTPUT

      - name: Set qualifier
        id: qualifierinfo
        run: |
          if [ "${BRANCH_NAME}" = "main" ]; then
            echo "qualifier=.${BRANCH_NAME}${{github.run_number}}" >> $GITHUB_OUTPUT
          else
            echo "qualifier=-${BRANCH_NAME}rc${{github.run_number}}" >> $GITHUB_OUTPUT
          fi

  downstream:
    needs: set-build-info
    env:
      now: ${{needs.set-build-info.outputs.now}}
      repo: ${{needs.set-build-info.outputs.repo}}
      branch: ${{needs.set-build-info.outputs.branch}}
      qualifier: ${{needs.set-build-info.outputs.qualifier}}
    runs-on: ubuntu-latest
    steps:
      - name: Set resolves version to env
        run: |
          echo "resolvedversion=OpenZiti.NET.native.${{ env.ZITI_SDK_C_BRANCH }}${repo}${qualifier}" >> $GITHUB_ENV
      - name: Echo it
        run: |
          echo "OpenZiti.NET.native.${{env.resolvedversion}}.nupkg"