name: Deploy Quickstart Containers

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print value
        run: echo ${{ inputs.environment }}
