name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: IfMain
        if: "$(echo $GITHUB_REF | grep -o 'refs/heads/main') == 'refs/heads/main'"
        run: |
          # This step will only run if the branch is 'main'
          echo "This step runs only on the 'main' branch"
