name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch is 'main'
        id: check_branch
        run: |
          echo "GIT_BRANCH=$(echo $GITHUB_REF | grep -o 'refs/heads/main')" >> $GITHUB_ENV

      - name: Set Qualifier
        run: |
          if [ "$is_main" = "refs/heads/main" ]; then
            echo "QUALIFIER=${GIT_BRANCH}" >> $GITHUB_ENV
          else
            echo "QUALIFIER=${GIT_BRANCH}" >> $GITHUB_ENV
          fi
