name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Set Qualifier
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "QUALIFIER=${BRANCH_NAME}-main" >> $GITHUB_ENV
          else
            echo "QUALIFIER=${BRANCH_NAME}-not-main" >> $GITHUB_ENV
          fi
          
      - name: Output Qualifier
        run: |
          echo "QUALIFIER is ${QUALIFIER}"
