name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  setbuildinfo:
    runs-on: ubuntu-latest
    outputs:
      now: ${{ steps.buildinfo.outputs.now }}
      repo: ${{ steps.buildinfo.outputs.repo }}
      qualifier: ${{ steps.buildinfo.outputs.qualifier }}
      branch: ${{ steps.buildinfo.outputs.qualifier }}
      buildnum: ${{ steps.buildinfo.outputs.buildnum }}
    steps:
      - name: Set now, repo, qualifier, branch, build num
        id: buildinfo
        run: |
          echo "now=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          if [ "${{ github.repository }}" == 'openziti/ziti-sdk-csharp' ]; then
            echo "repo=" >> $GITHUB_OUTPUT
          else
            echo "repo=-${{github.repository_owner}}" >> $GITHUB_OUTPUT
          fi
          echo "branch=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV
          if [ "${BRANCH_NAME}" = "main" ]; then
            echo "qualifier=" >> $GITHUB_OUTPUT
          else
            echo "qualifier=-rc" >> $GITHUB_OUTPUT
          fi
          echo "buildnum=.${{github.run_number}}" >> $GITHUB_OUTPUT
        
      - name: Set Branch Name
        id: set_branch
        run: |

  downstream:
    runs-on: ubuntu-latest
    needs: setbuildinfo
    steps:
      - env:
          now: ${{needs.setbuildinfo.outputs.now}}
          repo: ${{needs.setbuildinfo.outputs.repo}}
          qualifier: ${{needs.setbuildinfo.outputs.qualifier}}
          branch: ${{needs.setbuildinfo.outputs.branch}}
          buildnum: ${{needs.setbuildinfo.outputs.buildnum}}
        name: Echo outputs
        run: |
          echo "MyPackage${repo}${qualifier}${buildnum}"