name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch is 'main'
        id: check_branch
        run: |
          echo "GIT_BRANCH=$(echo $GITHUB_REF | grep -o 'refs/heads/main')" >> $GITHUB_ENV

      - name: If main
        if: "$GIT_BRANCH" == 'refs/heads/main'
        run: |
          # This step will only run if the branch is 'main'
          echo "This step runs only on the '${{ steps.check_branch.outputs.branch }}' branch"
          
      - name: If NOT main
        if: "$GIT_BRANCH" != 'refs/heads/main'
        run: |
          # This step will only run if the branch is 'main'
          echo "This is not the main branch: ${{ steps.check_branch.outputs.branch }}"
