name: OnDemand Action Test Because I Can't Run This Locally

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
        
jobs:
  set-build-info:
    runs-on: ubuntu-latest
    outputs:
      now: ${{ steps.buildinfo.outputs.now }}
      repo: ${{ steps.buildinfo.outputs.repo }}
    steps:
      - name: Set now, repo, qualifier, build num
        id: buildinfo
        run: |
          echo "now=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "repo=${github.repository_owner}" >> $GITHUB_OUTPUT
        
      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Set Qualifier
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "QUALIFIER=${BRANCH_NAME}-main" >> $GITHUB_ENV
          else
            echo "QUALIFIER=${BRANCH_NAME}-not-main" >> $GITHUB_ENV
          fi
          
      - name: Output Qualifier
        run: |
          echo "QUALIFIER is ${QUALIFIER}"

  downstream:
    runs-on: ubuntu-latest
    needs: set-build-info
    steps:
      - env:
          OUTPUT1: ${{needs.set-build-info.outputs.now}}
          OUTPUT2: ${{needs.set-build-info.outputs.repo}}
      - name: Echo outputs
        run: |
          echo "$OUTPUT1 $OUTPUT2"